version: '3.8'

services:
  webapp:
    build:
      context: ./FarhanS.Portfolio
      dockerfile: src/Web/Dockerfile
    platform: linux/arm64  # Optimized for M1 Mac
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=portfolio;User=root;Password=password;
    networks:
      - portfolio-network
    # Add restart policy for production-like behavior
    restart: unless-stopped
    # Add healthcheck
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  db:
    image: mysql:8.0
    platform: linux/arm64  # Optimized for M1 Mac
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=portfolio
    volumes:
      - mysql-data:/var/lib/mysql
      - ./sql-init:/docker-entrypoint-initdb.d
    networks:
      - portfolio-network
    # Add healthcheck for MySQL
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

networks:
  portfolio-network:
    driver: bridge

volumes:
  mysql-data: