FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["src/Web/FarhanS.Portfolio.csproj", "Web/"]
COPY ["src/Core/Core.csproj", "Core/"]
COPY ["src/Infrastructure/Infrastructure.csproj", "Infrastructure/"]
RUN dotnet restore "Web/FarhanS.Portfolio.csproj"
COPY src .
WORKDIR "/src/Web"
RUN dotnet build "FarhanS.Portfolio.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "FarhanS.Portfolio.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "FarhanS.Portfolio.dll"]