name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    
    - name: Restore dependencies
      run: dotnet restore FarhanS.Portfolio/FarhanS.Portfolio.sln
    
    - name: Build
      run: dotnet build FarhanS.Portfolio/FarhanS.Portfolio.sln --no-restore
    
    - name: Test
      run: dotnet test FarhanS.Portfolio/FarhanS.Portfolio.sln --no-build --verbosity normal
  
  docker-build-and-push:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./FarhanS.Portfolio
        file: ./FarhanS.Portfolio/src/Web/Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/portfolio:latest